apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "injector.name" . }}
  namespace: secret-operator-system
  labels:
    app.kubernetes.io/name: {{ include "injector.name" . }}
    helm.sh/chart: {{ include "injector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "injector.name" . }}    
      app.kubernetes.io/instance: {{ .Release.Name }}    
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "injector.name" . }}
        helm.sh/chart: {{ include "injector.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ include "injector.serviceAccountName" . }}
      containers:
      - name: agent-injector
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GSECRET_INJECTOR_AUTO_NAME
            value: {{ include "injector.name" . }}-webhook
          - name: GSECRET_INJECTOR_AUTO_HOST
            value: "{{ include "injector.name" . }},{{ include "injector.name" . }}.secret-operator-system,{{ include "injector.name" . }}.secret-operator-system.svc"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTPS
          failureThreshold: 2
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTPS
          failureThreshold: 2
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5    
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
