---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "injector.name" . }}-webhook
  namespace: secret-operator-system
  labels:
    app.kubernetes.io/name: {{ include "injector.name" . }}
    helm.sh/chart: {{ include "injector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
webhooks:
  - name: {{ include "injector.name" . }}.secret-operator-system.svc.cluster.local
    clientConfig:
      caBundle: {{ .Values.certs.caBundle }}
      service:
        name: {{ include "injector.name" . }}
        namespace: secret-operator-system
        path: "/mutate"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["deployments", "jobs", "pods", "statefulsets"]
    namespaceSelector: {}