apiVersion: v1
kind: Service
metadata:
  name: {{ include "injector.name" . }}
  namespace: secret-operator-system
  labels:
    app.kubernetes.io/name: {{ include "injector.name" . }}
    helm.sh/chart: {{ include "injector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "injector.name" . }}    
    app.kubernetes.io/instance: {{ .Release.Name }}    
