apiVersion: secret.security.imrenagi.com/v1alpha1
kind: GoogleSecretEntry
metadata:
  name: googlesecretentry-sample
spec:
  secretRef:
    name: some-secret
    namespace: default
    key: application-testing.json
  secrets:
  - path: projects/imre-demo/secrets/key1/versions/latest
    name: key1
  - path: projects/imre-demo/secrets/key2/versions/latest
    name: key2 
