apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-injector
  namespace: secret-operator-system
  labels: 
    app: agent-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-injector
  template:
    metadata:
      labels:
        app: agent-injector
    spec:
      serviceAccountName: "gsecret-agent-injector"
      containers:
      - name: agent-injector
        image: imrenagi/gsecret-agent-injector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GSECRET_INJECTOR_AUTO_NAME
            value: google-secret-injector-webhook
          - name: GSECRET_INJECTOR_AUTO_HOST
            value: "agent-injector,agent-injector.secret-operator-system,agent-injector.secret-operator-system.svc"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTPS
          failureThreshold: 2
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTPS
          failureThreshold: 2
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5                 